name: yarn test:repoutils

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'libraries/botbuilder-repo-utils/**'
    - '.github/workflows/run-test-repoutils.yml'
    branches: 
    - main

jobs:
  linux:
    name: yarn test:repoutils ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: yarn
        run: yarn

      - name: yarn test:repoutils
        run: yarn test:repoutils

  windows:
    name: yarn test:repoutils windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: yarn
        run: yarn

      - name: yarn test:repoutils
        run: yarn test:repoutils
