name: yarn test:consumer

on:
  workflow_dispatch:
  push:
    branches: 
    - main
    - 4.10
    - 4.11
  pull_request:
    branches: 
    - main
    - 4.10
    - 4.11

jobs:
  build:
    name: yarn test:consumer

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: yarn
        run: yarn --frozen-lockfile

      - name: yarn build
        run: yarn build

      - name: yarn test:consumer
        run: yarn test:consumer
