name: test-repoutils.yml

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - '4.12'
    - '4.13'
  pull_request:
    branches:
    - main
    - '4.12'
    - '4.13'

jobs:
  ci:
    name: test:repoutils
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: use node 22.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 22.x

      - name: yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node22.x-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: yarn
        run: yarn --frozen-lockfile

      - name: yarn test:repoutils
        run: yarn test:repoutils
